const $=x=>document.getElementById(x);let mode="login",user=null,chats=[],current=null,pending=null;
const users=()=>JSON.parse(localStorage.getItem("nova_users")||"{}"),saveUsers=x=>localStorage.setItem("nova_users",JSON.stringify(x));
function setMode(m){mode=m;$("lt").classList.toggle("active",m==="login");$("st").classList.toggle("active",m==="signup");$("name").classList.toggle("hide",m==="login");$("as").textContent=m==="login"?"دخول":"إنشاء حساب";$("ae").textContent=""}
$("lt").onclick=()=>setMode("login");$("st").onclick=()=>setMode("signup");
$("af").onsubmit=e=>{e.preventDefault();let u=users(),email=$("email").value.trim().toLowerCase(),pass=$("pass").value;if(mode==="signup"){let name=$("name").value.trim();if(!name){$("ae").textContent="اكتب اسمك.";return}if(u[email]){$("ae").textContent="الحساب موجود بالفعل.";return}u[email]={name,email,password:pass};saveUsers(u);enter(u[email])}else{if(!u[email]||u[email].password!==pass){$("ae").textContent="البريد أو كلمة المرور غير صحيحة.";return}enter(u[email])}};
function enter(x){user=x;let key="nova_chats_"+x.email;try{chats=JSON.parse(localStorage.getItem(key)||"[]")}catch{chats=[]}if($("remember").checked)localStorage.setItem("nova_session",x.email);else sessionStorage.setItem("nova_session",x.email);$("auth").classList.add("hide");$("app").classList.remove("hide");$("user").textContent=x.name;if(!chats.length)newChat();else select(chats[0].id);renderList()}
function persist(){localStorage.setItem("nova_chats_"+user.email,JSON.stringify(chats))}
function newChat(){let c={id:Date.now().toString(),title:"محادثة جديدة",messages:[]};chats.unshift(c);persist();select(c.id);renderList()}
$("new").onclick=newChat;$("logout").onclick=()=>{localStorage.removeItem("nova_session");sessionStorage.clear();location.reload()};
function select(id){current=chats.find(c=>c.id===id);render();renderList()}
function renderList(){$("list").innerHTML=chats.map(c=>`<div class="chat ${current&&current.id===c.id?"active":""}" data-id="${c.id}">${esc(c.title)}</div>`).join("");document.querySelectorAll(".chat").forEach(x=>x.onclick=()=>select(x.dataset.id))}
function esc(s){return String(s).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function add(role,text,image){let d=document.createElement("div");d.className="msg "+role;if(image){let i=document.createElement("img");i.src=image;d.appendChild(i)}let p=document.createElement("div");p.textContent=text;d.appendChild(p);$("msgs").appendChild(d)}
function render(){$("msgs").innerHTML="";if(!current.messages.length)add("ai","أهلاً! أنا NOVA AI ✦\nاسألني أي سؤال مفيد، ويمكنك إرفاق صورة.");current.messages.forEach(m=>add(m.role,m.text,m.image));$("msgs").scrollTop=$("msgs").scrollHeight}
$("img").onchange=()=>{let f=$("img").files[0];if(!f)return;if(f.size>6*1024*1024){alert("الصورة أكبر من 6MB");return}let r=new FileReader();r.onload=()=>{pending=r.result;$("pi").src=pending;$("prev").classList.remove("hide")};r.readAsDataURL(f)};
$("rm").onclick=()=>{pending=null;$("img").value="";$("prev").classList.add("hide")};
$("cf").onsubmit=async e=>{e.preventDefault();let text=$("text").value.trim();if(!text&&!pending)return;let image=pending;$("text").value="";pending=null;$("img").value="";$("prev").classList.add("hide");if(current.title==="محادثة جديدة")current.title=(text||"صورة").slice(0,30);current.messages.push({role:"user",text:text||"حلل الصورة من فضلك",image:image||null});persist();render();let d=document.createElement("div");d.className="msg ai";d.textContent="جارٍ التفكير...";$("msgs").appendChild(d);try{let msgs=current.messages.map(m=>m.image?{role:"user",content:[{type:"input_text",text:m.text},{type:"input_image",image_url:m.image}]}:{role:m.role,content:m.text});let r=await fetch("/api/chat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({messages:msgs})});let data=await r.json();if(!r.ok)throw Error(data.error||"حدث خطأ");d.textContent=data.text||"رد.";current.messages.push({role:"assistant",text:d.textContent});persist()}catch(err){d.textContent="تعذر الاتصال بـ NOVA AI: "+err.message}renderList()};
$("theme").onclick=()=>{document.body.classList.toggle("light");localStorage.setItem("nova_theme",document.body.classList.contains("light")?"light":"dark")};if(localStorage.getItem("nova_theme")==="light")document.body.classList.add("light");
$("text").onkeydown=e=>{if(e.key==="Enter"&&!e.shiftKey){e.preventDefault();$("cf").requestSubmit()}};
let s=localStorage.getItem("nova_session")||sessionStorage.getItem("nova_session"),all=users();if(s&&all[s])enter(all[s]);
